### ISSUE TITLE
Error when building "SocketCore.lo" on OS X 10.11

### ISSUE THREAD

**Issue by bonkboykz** [tatsuhiro-t/aria2#531] opened 2016-01-16 10:44 UTC
**$ ./configure**
```
version:        0.1.1 shared 0:0:0
    Host type:      x86_64-apple-darwin15.2.0
    Install prefix: /usr/local
    C compiler:     gcc
    CFlags:         -g -O2
    Library types:  Shared=yes, Static=yes
    CUnit:          no

 
Build:          x86_64-apple-darwin15.2.0
Host:           x86_64-apple-darwin15.2.0
Target:         x86_64-apple-darwin15.2.0
Install prefix: /usr/local
CC:             gcc
CXX:            g++
CPP:            gcc -E
CXXFLAGS:       -g -O2 -pipe -std=c++11 
CFLAGS:         -g -O2 -pipe
CPPFLAGS:       -I$(top_builddir)/deps/wslay/lib/includes -I$(top_srcdir)/deps/wslay/lib/includes  -I/usr/local/Cellar/libxml2/2.9.3/include/libxml2   -I/usr/local/include
LDFLAGS:         -framework CoreFoundation -framework Security
LIBS:           -lsqlite3 -L/usr/local/Cellar/libxml2/2.9.3/lib -lxml2 -lz -lpthread -liconv -lm -lz 
DEFS:           -DHAVE_CONFIG_H
LibUV:          
SQLite3:        yes
SSL Support:    yes
AppleTLS:       yes
WinTLS:         no
GnuTLS:         
OpenSSL:        
CA Bundle:      
LibXML2:        yes
LibExpat:       
LibCares:       no
Zlib:           yes
Libssh2:        no
Epoll:          
Bittorrent:     yes
Metalink:       yes
XML-RPC:        yes
Message Digest: apple
WebSocket:      yes
Libaria2:       no
bash_completion dir: ${datarootdir}/doc/${PACKAGE_TARNAME}/bash_completion
Static build:   
```
After executing **make** command:
```
SocketCore.cc:316:32: error: implicit instantiation of undefined template
      'std::__1::array<char, 1025>'
  std::array<char, NI_MAXHOST> host;
                               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: 
      template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
```

**Comment by tatsuhiro-t** [comment] 2016-01-17 12:02
duplicate of #530

**Closed by tatsuhiro-t** 2016-01-17 12:02 UTC
