### ISSUE TITLE
Hanging CLOSE_WAIT connection when in daemon mode

### ISSUE THREAD

**Issue by bremby** [tatsuhiro-t/aria2#477] opened 2015-11-11 06:45 UTC
I am using aria2 as a daemon listening on its RPC interface and being controlled by a web UI (https://github.com/ziahamza/webui-aria2). When all downloads are finished and stopped using that UI, aria2 closes almost all connections, (possibly) always leaving one connection hanging in the CLOSE_WAIT state. This seems to be an error on aria2's part.

This causes trouble for me because I am listing all open connections and using the result as one of the conditions for putting my server to sleep. Currently every time I download something, aria will keep one connection open, resulting in the server being running until I restart aria.

**Comment by tatsuhiro-t** [comment] 2015-11-11 12:39
Thank you for reporting this issue.
It seems that this bug is caused by pooled file descriptor.
aria2 by default pools file descriptor for reuse.  The thing is we only evict timed out file descriptor when we pool another file descriptor.  In this issue, we no longer pool anything, so no eviction, and no close.  I'm working on the fix.

**Comment by tatsuhiro-t** [comment] 2015-11-11 13:35
The above commit fixes this issue.

**Comment by bremby** [comment] 2015-11-11 13:49
Perfect, thank you. If I understand the code correctly, you attempt to evict descriptors every 30 seconds, am I right?
Anyway, thanks for such quick resolution. I would donate, but I didn't find any donation info.

**Comment by tatsuhiro-t** [comment] 2015-11-11 13:55
Yes, 30 seconds interval to run eviction.  I know we can go even smarter, but this is a simple fix without changing many part of aria2 codebase.

Thank you for donation, but it is a difficult time for OSS developer living in Japan.  Japanese law effectively prohibits donation without registering myself as some kind of organization eligible for donation.  Probably tax related regulation, but I don't know details.

**Comment by bremby** [comment] 2015-11-11 14:24
Sorry to hear that, that sucks.

Will you be making a new release? I am using Arch Linux, so no problem if you don't. Also, if you tested the fix, you can close the issue. I'll reopen it if necessary.

**Comment by tatsuhiro-t** [comment] 2015-11-11 14:29
OK, I close this issue.
More than 1 month passed from the last release, so I think it is good idea to make a new release.
Will schedule next release.  I think we can make it in this month or latest in this year.

**Closed by tatsuhiro-t** 2015-11-11 14:29 UTC
