### ISSUE TITLE
Torrent/Magnet won't start download issues...

### ISSUE THREAD

**Issue by alienx2** [tatsuhiro-t/aria2#504] opened 2015-12-12 15:41 UTC
I'm having problem with torrent/magnet won't start download... it still stuck long... i did tested download via http working fine but torrent/magnet is not.

my config:
daemon=true
continue=true
enable-rpc=true
rpc-listen-port=6800
rpc-listen-all=true
rpc-max-request-size=9M
save-session=/tmp/mnt/TOSHIBA/Download2/aria2_session.txt
input-file=/tmp/mnt/TOSHIBA/Download2/aria2_session.txt
dht-file-path=/tmp/mnt/TOSHIBA/Download2/DHT/dht.dat
dht-file-path6=/tmp/mnt/TOSHIBA/Download2/DHT/dht6.dat
enable-dht6=false
auto-save-interval=10
save-session-interval=10
dir=/tmp/mnt/TOSHIBA/Download2/httptor
log=/opt/var/log/aria2/aria2.log
log-level=error
dht-listen-port=6801
listen-port=6881-6999
seed-ratio=1.0
seed-time=1460
max-upload-limit=20K
event-poll=select
max-connection-per-server=8
max-concurrent-downloads=10
max-overall-download-limit=0
disable-ipv6=true
summary-interval=120

log:
2015-12-12 22:39:43.182098 ERROR - [DHTSetup.cc:107]Exception caught while loading DHT routing table from /tmp/mnt/TOSHIBA/Download2/DHT/dht.dat   
Exception: [DHTRoutingTableDeserializer.cc:72] errorCode=1 Failed to load DHT routing table.                                                       
2015-12-12 22:50:10.801200 ERROR - [DHTSetup.cc:107]Exception caught while loading DHT routing table from /tmp/mnt/TOSHIBA/Download2/DHT/dht.dat                     
Exception: [DHTRoutingTableDeserializer.cc:83] errorCode=1 Failed to load DHT routing table from /tmp/mnt/TOSHIBA/Download2/DHT/dht.dat

i installed via ipkg install aria2 and its version 1.14.2. (on Router)

**Comment by tatsuhiro-t** [comment] 2015-12-13 08:09
Could you share the torrent or magnet URI you encountered with this trouble? (just in case, we only investigate if they are legal torrents).

DHT requires routing table which includes the address of known peers, and it takes some time to build such routing table, aria2 saves it in a file.   Initially, aria2 does not know any peers, and there is no file.  The log says this situation.
When downloading torrent using .torrent file, DHT routing table is not required, and download should work.  While downloading, aria2 may get DHT peer information from connected peers, then it will save them in a file.
With magnet URI, usually aria2 has to use DHT to first get peer address, and then get torrent meta data from them. Some magnet URI has udp tracker address, which can skip DHT access.
If magnet URI does not udp tracker, then you need to specify bootstrap DHT peer with --dht-entry-point option.  See also http://stackoverflow.com/questions/1181301/how-does-a-dht-in-a-bittorent-client-get-bootstrapped

**Comment by alienx2** [comment] 2015-12-14 17:28
anyway i found out.. i did switched to entware from optware bec optware look old version... now its working =)

**Comment by tatsuhiro-t** [comment] 2015-12-15 13:34
OK, closing this issue.

**Closed by tatsuhiro-t** 2015-12-15 13:34 UTC

**Comment by nasht00** [comment] 2016-03-20 16:00
I have a computer with aria2c working.

I just got a new computer and installed aria2c on it.

I tried downloading the exact same torrent on both computer. On the old one, it works (13 seeds).
On the new one, I get 
`[ERROR] Exception caught while loading DHT routing table from /Users/nathanh/.cache/aria2/dht.dat
Exception: [../../../src/DHTRoutingTableDeserializer.cc:83] errorCode=1 Failed to load DHT routing table from /Users/nathanh/.cache/aria2/dht.dat`

**Comment by Zenexer** [comment] 2017-06-11 23:58
Now encountering this issue on Bash on Windows.  MinGW seems to be having the same problem: https://github.com/Alexpux/MINGW-packages/issues/245

**Comment by Zenexer** [comment] 2018-06-16 02:47
Also encountering this issue with aria2c installed from Chocolatey repos.

**Comment by AntonFriberg** [comment] 2018-12-21 22:44
Experienced this problem as well using the latest 1.34.0 version. It seems to have been caused by not having enough available disk space to download the torrent in my case at least. One I made more disk space available the problem resolved itself.

**Comment by totedati** [comment] 2019-12-31 02:13
To me that error, _Failed to load DHT routing table from .dat_,  appear only at first run if you dont have already one. After one CTRL+C and a new run error dissapear because now i have some peers in .dat
