### ISSUE TITLE
Different file name while downloading process

### ISSUE THREAD

**Issue by tommyziegler** [tatsuhiro-t/aria2#380] opened 2015-05-07 14:10 UTC
Is there a way how to setup Aria2 that while downloading the file is with a .part ending allocated on hardest and only in case the download is successful, the file will be named correct!?

Is there already a way how to achieve it? Because I went through complete documentation and didn't found any possibility.

Would that be a feature request? Are you even at the moment extending it? Do you have time? I would need this feature. I at the moment have not got work the project but when you don't have time and if we yourself could add it is it possible that you merge it?

Thanks

Tommy

**Comment by tatsuhiro-t** [comment] 2015-05-07 14:45
This is duplicate of #284 
I have no objection to add this feature, but we have no plan to add this at the moment.

**Comment by Deadooshka** [comment] 2015-05-09 00:01
aria --out=filename.part --on-download-complete="/script to remove .part" url

**Comment by tatsuhiro-t** [comment] 2016-01-29 01:49
Closing since this is duplicate

**Closed by tatsuhiro-t** 2016-01-29 01:49 UTC
