### ISSUE TITLE
Issue with metalink + multi-file torrent

### ISSUE THREAD

**Issue by dustymabe** [tatsuhiro-t/aria2#607] opened 2016-03-26 17:15 UTC
Hi. Thanks for the great work on aria2 and metalink.

I am trying to create a metalink file to download the Fedora 23 server DVD iso. I want to include the torrent information in this metalink. The [torrent file] (https://torrent.fedoraproject.org/torrents/Fedora-Server-DVD-x86_64-23.torrent) provided by fedora has two files in it:
```
[root@f23vanilla bin]# aria2c -S Fedora-Server-DVD-x86_64-23.torrent 
>>> Printing the contents of file 'Fedora-Server-DVD-x86_64-23.torrent'...
*** BitTorrent File Information ***
Creation Date: Tue, 03 Nov 2015 01:40:50 GMT
Mode: multi
Announce:
 http://torrent.fedoraproject.org:6969/announce
Info Hash: 54a2ba1c02a2f07a8f4d48754c52088dc4ed7b58
Piece Length: 256KiB
The Number of Pieces: 8201
Total Length: 2.0GiB (2,149,581,942)
Name: Fedora-Server-DVD-x86_64-23
Magnet URI: magnet:?xt=urn:btih:54A2BA1C02A2F07A8F4D48754C52088DC4ED7B58&dn=Fedora-Server-DVD-x86_64-23&tr=http%3A%2F%2Ftorrent.fedoraproject.org%3A6969%2Fannounce
Files:
idx|path/length
===+===========================================================================
  1|./Fedora-Server-DVD-x86_64-23/Fedora-Server-23-x86_64-CHECKSUM
   |1.1KiB (1,142)
---+---------------------------------------------------------------------------
  2|./Fedora-Server-DVD-x86_64-23/Fedora-Server-DVD-x86_64-23.iso
   |2.0GiB (2,149,580,800)
---+---------------------------------------------------------------------------
```

The `meta4` file I have created for this is reproduced below:
```xml
<?xml version="1.0" encoding="utf-8"?>
<metalink version="4.0" xmlns="urn:ietf:params:xml:ns:metalink">
  <file name="Fedora-Server-DVD-x86_64-23.iso">
    <description>Fedora Server DVD</description>
    <size>2149580800</size>
    <version>23</version>
    <hash type="sha-256">30758dc821d1530de427c9e35212bd79b058bd4282e64b7b34ae1a40c87c05ae</hash>
    <metaurl mediatype="torrent" name="Fedora-Server-DVD-x86_64-23/Fedora-Server-DVD-x86_64-23.iso" priority="2">https://torrent.fedoraproject.org/torrents/Fedora-Server-DVD-x86_64-23.torrent</metaurl>
  </file>
</metalink>
```

But when I try to download with `aria2c` (from aria2-1.19.3-1.fc23.x86_64 on fedora) I get the following:
```
[root@f23vanilla bin]# aria2c fedora.meta4 

03/26 17:05:24 [NOTICE] Download complete: /root/rpmbuild/BUILDROOT/wget-1.17.1-1.fc23.x86_64/usr/bin/Fedora-Server-DVD-x86_64-23.torrent

03/26 17:05:24 [ERROR] Exception caught
Exception: [BtDependency.cc:151] errorCode=1 No entry  in torrent file

03/26 17:05:24 [NOTICE] Download GID#5a5ab91607d24533 not complete: /root/rpmbuild/BUILDROOT/wget-1.17.1-1.fc23.x86_64/usr/bin/Fedora-Server-DVD-x86_64-23.iso

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
5a5ab9|ERR |       0B/s|/root/rpmbuild/BUILDROOT/wget-1.17.1-1.fc23.x86_64/usr/bin/Fedora-Server-DVD-x86_64-23.iso

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
```

I don't know if this is a bug in aria2 or if it is a bug in the .meta4 file I created. Can you verify that this is not a bug in aria2? 

Thanks,
Dusty

**Comment by tatsuhiro-t** [comment] 2016-03-27 10:31
Thank you for telling me this.  I think 395b8e9 fixes this bug.

**Comment by dustymabe** [comment] 2016-03-27 17:54
That seems to do the trick. I applied the patch to the version and fedora and it works now.

A few questions:
- After the download the directory and the other file from the torrent still exists on the machine. Is it possible to just download the single file from the torrent rather than the collection of files? This might not be possible but I just don't know because I don't fully understand torrents. If not, should we clean up the other files and the directory after download?
- Does aria2c verify the contents match checksum from the metalink? I don't see any indication of that from the output:
```
 *** Download Progress Summary as of Sun Mar 27 17:48:47 2016 ***                                                                                                                                                                                                             
==============================================================================================================================================================================================================================================================================
[#921325 1.9GiB/2.0GiB(97%) CN:45 SD:42 DL:4.0MiB ETA:10s]
FILE: /root/foo/Fedora-Server-DVD-x86_64-23.iso
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[#921325 2.0GiB/2.0GiB(99%) CN:44 SD:41 DL:3.9MiB]                                                                                                                                                                                                                            
03/27 17:49:06 [NOTICE] Download of selected files was complete.
 *** Download Progress Summary as of Sun Mar 27 17:49:48 2016 ***                                                                                                                                                                                                             
==============================================================================================================================================================================================================================================================================
[#921325 SEED(0.0) CN:2 SD:0]
FILE: /root/foo/Fedora-Server-DVD-x86_64-23.iso
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[#921325 SEED(0.0) CN:2 SD:0]^C                                                                                                                                                                                                                                               
03/27 17:50:08 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.
```

**Comment by tatsuhiro-t** [comment] 2016-04-10 03:48
> After the download the directory and the other file from the torrent still exists on the machine. Is it possible to just download the single file from the torrent rather than the collection of files? This might not be possible but I just don't know because I don't fully understand torrents. If not, should we clean up the other files and the directory after download?

This is by design at the moment.  Due to the arrangement of piece hash of torrent files, we need adjacent files to download a wanted file.  It could be implemented more elegantly, but there is no effort to make it happen so far.

> Does aria2c verify the contents match checksum from the metalink? I don't see any indication of that from the output:

If checksums are available from both metalink and torrent file, only the ones from torrent file is used.

**Comment by tatsuhiro-t** [comment] 2016-04-10 03:48
I close this issue, since the original issue has been fixed.

**Closed by tatsuhiro-t** 2016-04-10 03:48 UTC
Labels: bug
