### ISSUE TITLE
SSL downloads problem from sendspace.com

### ISSUE THREAD

**Issue by Denisov39** [tatsuhiro-t/aria2#451] opened 2015-08-28 07:40 UTC
Hi !

aria2 1.18.0. Debian 7.
When i try to download file from sendspace.com, i get this error

2015-08-28 10:25:11.701075 [DEBUG] [FeedbackURISelector.cc:84] FeedbackURISelector selected https://fs09n3.sendspace.com/dl/d090efad059c1d8becce5deb2d0ead7c/55e00cd03c87a6e4/gx06xn/%28Sample%29%20Any%20Body%20Ca
n%20Dance%202%20%282015%29%20DVDRip%20-%20x264%20-%201CDRip%20-%20ESub%20-%20%5BDDR%5D.mkv
2015-08-28 10:25:11.701124 [DEBUG] [AbstractCommand.cc:187] CUID#26 - socket: read:0, write:0, hup:0, err:0
2015-08-28 10:25:11.702293 [INFO] [AsyncNameResolverMan.cc:89] CUID#26 - Resolving hostname fs09n3.sendspace.com
2015-08-28 10:25:11.703438 [DEBUG] [EpollEventPoll.cc:261] Failed to delete socket event:Wrong file descriptor.
2015-08-28 10:25:11.703465 [DEBUG] [AbstractCommand.cc:187] CUID#26 - socket: read:0, write:0, hup:0, err:0
2015-08-28 10:25:11.703555 [INFO] [AbstractCommand.cc:829] CUID#26 - Name resolution complete: fs09n3.sendspace.com -> 69.31.136.41
2015-08-28 10:25:11.703582 [INFO] [HttpInitiateConnectionCommand.cc:130] CUID#26 - Connecting to 69.31.136.41:443
2015-08-28 10:25:11.823698 [DEBUG] [AbstractCommand.cc:187] CUID#26 - socket: read:0, write:1, hup:0, err:0
2015-08-28 10:25:11.823797 [DEBUG] [AbstractCommand.cc:187] CUID#26 - socket: read:0, write:1, hup:0, err:0
2015-08-28 10:25:11.823808 [DEBUG] [SocketCore.cc:844] Creating TLS session
2015-08-28 10:25:11.823844 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Allocating epoch #0
2015-08-28 10:25:11.824047 [DEBUG] [SocketCore.cc:865] TLS Handshaking
2015-08-28 10:25:11.824067 [DEBUG] [Platform.cc:81] GnuTLS: <2> ASSERT: gnutls_constate.c:695
2015-08-28 10:25:11.824076 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Allocating epoch #1
2015-08-28 10:25:11.824271 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_RSA_AES_128_CBC_SHA256
2015-08-28 10:25:11.824282 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_RSA_AES_128_CBC_SHA1
2015-08-28 10:25:11.824291 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_RSA_CAMELLIA_128_CBC_SHA1
2015-08-28 10:25:11.824299 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_RSA_3DES_EDE_CBC_SHA1
2015-08-28 10:25:11.824307 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_DSS_AES_128_CBC_SHA256
2015-08-28 10:25:11.824315 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_DSS_AES_128_CBC_SHA1
2015-08-28 10:25:11.824322 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_DSS_CAMELLIA_128_CBC_SHA1
2015-08-28 10:25:11.824330 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_DSS_3DES_EDE_CBC_SHA1
2015-08-28 10:25:11.824338 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: DHE_DSS_ARCFOUR_SHA1
2015-08-28 10:25:11.824345 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: RSA_AES_128_CBC_SHA256
2015-08-28 10:25:11.824353 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: RSA_AES_128_CBC_SHA1
2015-08-28 10:25:11.824360 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: RSA_CAMELLIA_128_CBC_SHA1
2015-08-28 10:25:11.824373 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: RSA_3DES_EDE_CBC_SHA1
2015-08-28 10:25:11.824381 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: Keeping ciphersuite: RSA_ARCFOUR_SHA1
2015-08-28 10:25:11.824417 [DEBUG] [Platform.cc:81] GnuTLS: <2> EXT[0x2276860]: Sending extension SERVER NAME (25 bytes)
2015-08-28 10:25:11.824433 [DEBUG] [Platform.cc:81] GnuTLS: <2> EXT[0x2276860]: Sending extension SAFE RENEGOTIATION (1 bytes)
2015-08-28 10:25:11.824456 [DEBUG] [Platform.cc:81] GnuTLS: <2> EXT[SIGA]: sent signature algo (4.1) RSA-SHA256
2015-08-28 10:25:11.824466 [DEBUG] [Platform.cc:81] GnuTLS: <2> EXT[SIGA]: sent signature algo (2.2) DSA-SHA1
2015-08-28 10:25:11.824474 [DEBUG] [Platform.cc:81] GnuTLS: <2> EXT[0x2276860]: Sending extension SIGNATURE ALGORITHMS (6 bytes)
2015-08-28 10:25:11.824498 [DEBUG] [Platform.cc:81] GnuTLS: <3> HSK[0x2276860]: CLIENT HELLO was sent [117 bytes]
2015-08-28 10:25:11.824509 [DEBUG] [Platform.cc:81] GnuTLS: <6> BUF[HSK]: Inserted 117 bytes of Data
2015-08-28 10:25:11.824521 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Sending Packet[0] Handshake(22) with length: 117
2015-08-28 10:25:11.824538 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Sent Packet[1] Handshake(22) with length: 122
2015-08-28 10:25:11.944533 [DEBUG] [AbstractCommand.cc:187] CUID#26 - socket: read:1, write:0, hup:0, err:0
2015-08-28 10:25:11.944632 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Expected Packet[0] Handshake(22) with length: 1
2015-08-28 10:25:11.944642 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Received Packet[0] Alert(21) with length: 2
2015-08-28 10:25:11.944662 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Decrypted Packet[0] Alert(21) with length: 2
2015-08-28 10:25:11.944733 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Alert[2|40] - Handshake failed - was received
2015-08-28 10:25:11.944742 [DEBUG] [Platform.cc:81] GnuTLS: <2> ASSERT: gnutls_record.c:726
2015-08-28 10:25:11.944751 [DEBUG] [Platform.cc:81] GnuTLS: <2> ASSERT: gnutls_record.c:1122
2015-08-28 10:25:11.944760 [DEBUG] [Platform.cc:81] GnuTLS: <2> ASSERT: gnutls_handshake.c:2762
2015-08-28 10:25:11.944766 [DEBUG] [Platform.cc:81] GnuTLS: <6> BUF[HSK]: Cleared Data from buffer
2015-08-28 10:25:11.945223 [ERROR] [AbstractCommand.cc:350] CUID#26 - Download aborted. URI=https://fs09n3.sendspace.com/dl/d090efad059c1d8becce5deb2d0ead7c/55e00cd03c87a6e4/gx06xn/%28Sample%29%20Any%20Body%20Ca
n%20Dance%202%20%282015%29%20DVDRip%20-%20x264%20-%201CDRip%20-%20ESub%20-%20%5BDDR%5D.mkv
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://fs09n3.sendspace.com/dl/d090efad059c1d8becce5deb2d0ead7c/55e00cd03c87a6e4/gx06xn/%28Sample%29%20Any%20Body%20Can%20Dance%202%20%282015%29%20DVDRip%20-%
20x264%20-%201CDRip%20-%20ESub%20-%20%5BDDR%5D.mkv
  -> [SocketCore.cc:933] errorCode=1 SSL/TLS handshake failure: A TLS fatal alert has been received.
2015-08-28 10:25:11.945252 [DEBUG] [AbstractCommand.cc:474] CUID#26 - Aborting download
2015-08-28 10:25:11.945260 [DEBUG] [AbstractCommand.cc:420] CUID#26 - Not trying next request. No reserved/pooled request is remaining and total length is still unknown.
2015-08-28 10:25:11.945288 [DEBUG] [RequestGroup.cc:931] GID#f28e59f64564f3c8 - Request queue check
2015-08-28 10:25:11.945308 [DEBUG] [Platform.cc:81] GnuTLS: <2> ASSERT: gnutls_record.c:276
2015-08-28 10:25:11.945320 [DEBUG] [Platform.cc:81] GnuTLS: <6> BUF[HSK]: Cleared Data from buffer
2015-08-28 10:25:11.945351 [DEBUG] [Platform.cc:81] GnuTLS: <4> REC[0x2276860]: Epoch #0 freed

If check-certificate=false - same error.

Please help me resolve this problem.

Regards, Pavel.

**Comment by tatsuhiro-t** [comment] 2015-08-28 13:54
This could be a duplicate of #392.
If so, the fix was committed into master branch.

**Comment by tatsuhiro-t** [comment] 2016-01-29 02:30
Reopen this if you still experience this issue with the latest version.

**Closed by tatsuhiro-t** 2016-01-29 02:30 UTC
