### ISSUE TITLE
bcrypt.dll missing in XP with last aria2-1.19.0

### ISSUE THREAD

**Issue by lollita** [tatsuhiro-t/aria2#393] opened 2015-05-24 19:58 UTC
This application has failed to start because bcrypt.dll was not found. Re-installing the application may fix this problem.

**Comment by tatsuhiro-t** [comment] 2015-05-25 15:52
Thanks.  Could you tell us which software needs to be re-installed to make bcrypt.dll available?  Can we  download that software from Microsoft web site?

**Comment by lollita** [comment] 2015-05-25 18:02
The bcrypt.dll doesn't exist on XP, but it does on Vista, so this trick will only work on older Windows.
There is no redist version of the bcrypt.dll or its dependencies that can be deployed to a Windows XP or older system.
https://supportxpdotcom.wordpress.com/2013/02/23/casablanca-c-rest-sdk-xp-support/

**Comment by tatsuhiro-t** [comment] 2015-05-26 14:36
Thanks.  Probably we deprecate XP support for now, since it is too old and insecure.

**Comment by lollita** [comment] 2015-05-28 06:08
And I deprecate Aria2 update since it not support XP solid OS for geeks ;)

**Comment by tatsuhiro-t** [comment] 2015-05-28 12:32
OK, then we just agreed that aria2 support on XP platform is over.  Closing the issue.

**Closed by tatsuhiro-t** 2015-05-28 12:32 UTC

**Comment by lorien-mudak** [comment] 2015-09-01 04:26
We just agreed that you are a retard. Is there a real reason for dropping Xp?

As for insecurity - go try attack windows behind NAT/built-in firewall.

**Comment by tatsuhiro-t** [comment] 2015-09-01 12:45
One reason is we don't have a machine XP installed.  We cannot do any debugging on it.

I think this issue is only raised if aria2 is built with Windows native TLS library (schannel).
If aria2 is built with openssl, then probably it works without offending dll.  But you have to manage CA certificates.

I have to say this is opensource project, and we do this in completely voluntary basis.
If you want Windows native TLS support for XP, write a patch and send us PR, or find someone to do that.

**Comment by lorien-mudak** [comment] 2015-09-01 13:17
>If aria2 is built with openssl, then probably it works without offending dll. But you have to manage CA certificates.
So? That's exactly how wget and curl work. How do you work on lunix? Use openssl? Why not to do it on windows?

I think you mix opensource with open development. Opensource only means there are sources available.

**Comment by tatsuhiro-t** [comment] 2015-09-01 13:23
We choose Win TLS because CA is managed by OS.
If you don't like that, you can build windows build with openssl.
For Linux, it depends on the distribution.  In Debian/Ubuntu, aria2 package is built with GNUTLS, and it looks up /etc/ssl/certs/ca-certificates.crt.

**Comment by lorien-mudak** [comment] 2015-09-01 14:22
Windows users don't build anything, dude, they download an installer. Can you build both?

**Comment by tatsuhiro-t** [comment] 2015-09-01 14:51
We only build Win TLS version only.  That's too much work for us to build many configurations and testing them.

**Comment by lorien-mudak** [comment] 2015-09-01 15:01
And you are building wrong the one, that's why you are retarded.

**Comment by tatsuhiro-t** [comment] 2015-09-01 15:05
Well, then I don't want to waste my precious time with the person who calls us "retarded". I'm done with this.

**Comment by lorien-mudak** [comment] 2015-09-01 15:31
There is no reason to lose users. I would understand if there were a real reason, but you behave like microsoft - drop XP support because of 1 Mb DLL

**Comment by kazalex** [comment] 2015-09-03 22:07
I will have to replace aria2 by other downloader :( It is a pity. --userCount;

**Comment by ievgen-baida** [comment] 2015-09-04 15:16
Hi guys,
I am sorry to see this discussion went to nowhere.
We have the same issue on our Windows Home Server (based on Windows 2003).
Is there any way to have Aria2 running on Windows 2003?
Pleeeeeease :)

**Comment by clamsawd** [comment] 2015-10-03 20:22
@lorien-mudak @kazalex @ievgen-baida I have compiled aria2 1.19.1 using OpenSSL. Probably works on Windows XP/Server 2003 but I can't test it because I only have Windows 10 (works fine). Can you test it in your system and tell me?

aria2 1.19.1 builds (OpenSSL):

* [aria2-1.19.1-win-32bit-build3.7z] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.1-win-32bit-build3.7z)
* [aria2-1.19.1-win-64bit-build3.7z] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.1-win-64bit-build3.7z)

**Comment by lollita** [comment] 2015-10-03 20:28
123M is very high size.
I hope you will keep even a normal version.

**Comment by clamsawd** [comment] 2015-10-03 20:44
@lorien-mudak @kazalex @ievgen-baida If don't work the previous packages, try with this:

* [aria2-1.19.1-win-XP-build3.7z] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.1-win-XP-build3.7z)

All builds are static, the size of binaries is bigger but should work better.

**Comment by clamsawd** [comment] 2015-10-04 08:28
@tatsuhiro-t The problem with "bcrypt.dll" isn't WinTLS or OpenSSL. The problem is with sftp support, when you disable sftp (libssh), aria2 works in Windows XP because don't need bcrypt.dll library.

If you want keep the compatibility with Windows XP, only is necessary a package with sftp support (Windows Vista and Later) and other without sftp (Windows XP). I think the same that you, XP is an insecure and obsolete OS, is better upgrade to other Windows OS, but is simple still keep the compatibility with this simple step.

**Comment by tatsuhiro-t** [comment] 2015-10-04 08:34
We only build one configuration of windows build.
So if you all don't want sftp, then we kill it in windows build, and not distribute sftp enabled version of windows binary.
But then sftp user on windows may complain about lack of it.  So it would be better to let someone build custom binary and distribute it on their own.

**Comment by clamsawd** [comment] 2015-10-04 11:44
@lollita I added new builds of aria2 1.19.2. Now, the size of binaries are correct (5,8MB is the size for Windows XP build).

aria2 1.19.2 builds (OpenSSL):

* [aria2-1.19.2-linux-gnu-32bit-build1.tar.bz2] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.2-linux-gnu-32bit-build1.tar.bz2)
* [aria2-1.19.2-linux-gnu-64bit-build1.tar.bz2] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.2-linux-gnu-64bit-build1.tar.bz2)
* [aria2-1.19.2-win-32bit-build1.7z] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.2-win-32bit-build1.7z)
* [aria2-1.19.2-win-64bit-build1.7z] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.2-win-64bit-build1.7z)
* [aria2-1.19.2-win-xp-build1.7z] (https://github.com/clamsawd/aria2-static-builds/raw/master/builds/aria2-1.19.2-win-xp-build1.7z)

All builds: https://github.com/clamsawd/aria2-static-builds

**Comment by kazalex** [comment] 2015-10-04 12:59
@clamsawd Fine works on mine XP. Many thanks!

**Comment by clamsawd** [comment] 2015-10-04 13:20
@kazalex From now on, when released a new version of aria2, the builds will be published in https://github.com/clamsawd/aria2-static-builds. I'm glad that work well in your XP!

**Comment by kazalex** [comment] 2015-10-04 13:23
@clamsawd It a good news, thank!

**Comment by clamsawd** [comment] 2015-10-17 15:57
@kazalex I recompiled aria2 1.19.2 and now I have a generic binary with SFTP support that should run on all Windows versions (XP included). Can you try it and tell me if really run correctly on XP?

* [aria2-1.19.2-win-32bit-build2.7z](https://github.com/clamsawd/aria2-static-builds/releases/download/v1.19.2_2/aria2-1.19.2-win-32bit-build2.7z)

**Comment by kazalex** [comment] 2015-10-17 18:58
@clamsawd Checked on XP SP3. OK.

**Comment by clamsawd** [comment] 2015-10-17 19:00
@kazalex Perfect! Thanks.

**Comment by neoedmund** [comment] 2015-10-23 08:03
@clamsawd  hi, thank you for your aria2-1.19.2-win-32bit-build2.7z  
I tried to download from a HTTPS url with it on Windows XP machine but it complains:
```
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://xxxxxx
  -> [SocketCore.cc:975] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate
```
Do I need to install some CA file and how to ?
Thanks in advance.

**Comment by clamsawd** [comment] 2015-10-23 08:11
@neoedmund The instructions and certificates are here -> [https://github.com/clamsawd/aria2-static-builds](https://github.com/clamsawd/aria2-static-builds/blob/master/README.md)
Ask me if you have questions or do not understand something.

**Comment by neoedmund** [comment] 2015-10-23 08:27
@clamsawd On my windows xp machine, the file `aria2.conf` and the dir are not existed, I manually created and edited it.  It worked! It also works with `aria2c --ca-certificate=<PATH-TO-CERTIFICATE> <URL>` in command line.  
The problem is solved and thank you for your help!

**Comment by clamsawd** [comment] 2015-10-23 08:29
@neoedmund :+1:

**Comment by firstrose** [comment] 2015-11-20 02:22
aria2-1.19.2-win-32bit-build1.7z works on Win2003

Thank you!

**Comment by webdev20** [comment] 2015-12-25 21:04
XP is still widely used, not supporting XP means ignoring part of the market!

**Comment by justingoldberg** [comment] 2016-01-23 15:48
Just download it:

https://www.google.com/search?client=opera&q=%22index+of%22+bcrypt.dll&sourceid=opera&ie=utf-8&oe=utf-8&channel=suggest&gws_rd=ssl
