### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by pedropetz** [tatsuhiro-t/aria2#340] opened 2015-02-15 01:46 UTC
[ppetz@petzMJ ~]$ aria2c http://softlayer-ams.dl.sourceforge.net/project/manjarolinux/release/0.8.12/xfce/manjaro-xfce-0.8.12-x86_64.iso
aria2c: SimpleRandomizer.cc:93: void aria2::SimpleRandomizer::getRandomBytes(unsigned char*, size_t): Assertion `rv >= 0 && (size_t)rv == len' failed.
Aborted (core dumped)

**Comment by tatsuhiro-t** [comment] 2015-02-15 07:58
Duplicate of #336 and already fixed in master branch.

**Closed by tatsuhiro-t** 2015-02-15 07:58 UTC
