### ISSUE TITLE
File allocation on Windows

### ISSUE THREAD

**Issue by amirotin** [tatsuhiro-t/aria2#482] opened 2015-11-18 15:46 UTC
Greetings. Got the following situation:
OS WIndows 7 (Embedded edition)
Filesystem - NTFS

What i want - after downloading torrent move files to another drive (or drive pool), make symlink and start seeding. There is no problem when file-allocation is none or prealloc.

When i set file-allocation=falloc - files are created, explorer shows size as in torrent, but download stucks for some time ~ time of file allocation. And then it's ok with seeding over symlink.

When i set file-allocation=trunc - files are created, size is normal and download starts immediately. But after moving and symlinking i got errors:

```
11/18 18:40:59 [WARN] Making file sparse failed or pending: Incorrect function.
11/18 18:40:59 [WARN] Making file sparse failed or pending: Incorrect function.
11/18 18:40:59 [WARN] Making file sparse failed or pending: Incorrect function.
11/18 18:40:59 [WARN] Making file sparse failed or pending: Incorrect function.
11/18 18:40:59 [WARN] Making file sparse failed or pending: Incorrect function.
```

About torrent states -  i move files after i call pause on torrent. And then i call unpause.
What's interesting - most often it occurs with multi-file torrents.

**Comment by amirotin** [comment] 2015-11-18 16:28
With additional log i got this

```
2015-11-18 19:16:56.555068 [WARN] [AbstractDiskWriter.cc:470] Making file sparse failed or pending: Incorrect function.
```

**Comment by tatsuhiro-t** [comment] 2015-11-21 07:22
Probably, this is limitation of NTFS + sparse files, or some sort.
For me, sparse files on NTFS (or Windows API in general) is still rather black magic.
The relevant part of the code is
https://github.com/tatsuhiro-t/aria2/blob/9bce4eb925794528b21b4cdb0f7777ac24ffd7c2/src/AbstractDiskWriter.cc#L473

**Comment by amirotin** [comment] 2015-11-21 09:31
I think the problem is with the control file. When i pause finished torrent - control file still exists. And probably when symlink is created aria2 decided that torrent is not compled and is trying to allocate files again.

I've read documentation, but i don't understand when control file is deleted?

**Comment by tatsuhiro-t** [comment] 2015-11-21 09:45
A control file is removed when download was finished.
But if `--force-save` is used, they are not removed.

**Comment by amirotin** [comment] 2015-11-21 11:59
I've tested multiple combination of options. In all cases when torrent is multi-file, after i unpause torrent aria2 is trying to allocate files.

Single-file torrent has no problems with allocate, it just starts seeding after unpause.
The only way i got it working with multi-file - set file-allocation=none.

This error `Making file sparse failed or pending: Incorrect function.` occurs only when symlink is on another drive. When it is symlinking on the same drive - it stucks on `FileAlloc 100%`.

**Comment by tatsuhiro-t** [comment] 2015-11-21 13:27
We use same code to allocate space for both single and multi file torrent.
BTW, do you symlink to each file, or just a top level directory?

**Comment by amirotin** [comment] 2015-11-21 13:29
Only files inside folder and any subfolder. So folder structure stays as is.

**Comment by tatsuhiro-t** [comment] 2015-11-21 13:30
So if you have 100 files in multi torrent, do you create 100 symlinks?

**Comment by amirotin** [comment] 2015-11-21 13:31
Yes :)

**Comment by tatsuhiro-t** [comment] 2015-11-21 15:39
c2157e608e8225040cf3cc0d288a2c641d33f14c fixes the bug that file allocation gets stuck at 100%.
I could not reproduce "Incorrect function." error since I don't have necessary environment.

**Comment by amirotin** [comment] 2015-11-22 20:10
I've build aria2 with your fix. After testing all day i got following:

1. The problem is not with aria2, it with pooling software "DriveBender". When i symlink to another drive (not in pool) - it's ok.
2. Your fix is working great - no problem with symlink to same drive
3. When i enable check-integrity - aria2 shows "checksum" in console. And it's ok. Right after checksum it writes error. So the file is determined normal
4. You added log in MultiFileAllocationIterator.cc. It shows "current size=0". I think file size detection is wrong :(

Here is logs from single-file torrent

```
2015-11-22 22:51:15.720686 [NOTICE] [CheckIntegrityCommand.cc:77] Verification finished successfully. file=T:/Finished/Перевозчик Наследие..2015.D.HDRip.745MB..avi
2015-11-22 22:51:15.721686 [INFO] [FileAllocationDispatcherCommand.cc:57] Dispatching FileAllocationCommand for CUID#20.
2015-11-22 22:51:15.721686 [WARN] [AbstractDiskWriter.cc:476] Making file sparse failed or pending: Incorrect function.
2015-11-22 22:51:15.722686 [DEBUG] [FileAllocationCommand.cc:78] 0 seconds to allocate 780572672 byte(s)
```

logs from multi-file torrent

```
2015-11-22 23:02:26.677551 [NOTICE] [CheckIntegrityCommand.cc:77] Verification finished successfully. file=T:/Finished/Ash vs Evil Dead (Season 01) Goblin
2015-11-22 23:02:26.677551 [INFO] [FileAllocationDispatcherCommand.cc:57] Dispatching FileAllocationCommand for CUID#19.
2015-11-22 23:02:26.677551 [INFO] [MultiFileAllocationIterator.cc:99] Allocating file T:/Finished/Ash vs Evil Dead (Season 01) Goblin/Ash.vs.Evil.Dead.S01E01.XviD.Goblin.[qqss44].avi: target size=524339200, current size=0
2015-11-22 23:02:26.677551 [WARN] [AbstractDiskWriter.cc:476] Making file sparse failed or pending: Incorrect function.
2015-11-22 23:02:26.677551 [INFO] [MultiFileAllocationIterator.cc:99] Allocating file T:/Finished/Ash vs Evil Dead (Season 01) Goblin/Ash.vs.Evil.Dead.S01E02.XviD.Goblin.[qqss44].avi: target size=367988736, current size=0
2015-11-22 23:02:26.677551 [WARN] [AbstractDiskWriter.cc:476] Making file sparse failed or pending: Incorrect function.
2015-11-22 23:02:26.677551 [INFO] [MultiFileAllocationIterator.cc:99] Allocating file T:/Finished/Ash vs Evil Dead (Season 01) Goblin/Ash.vs.Evil.Dead.S01E03.XviD.Goblin.[qqss44].avi: target size=349990912, current size=0
2015-11-22 23:02:26.677551 [WARN] [AbstractDiskWriter.cc:476] Making file sparse failed or pending: Incorrect function.
2015-11-22 23:02:26.677551 [INFO] [MultiFileAllocationIterator.cc:99] Allocating file T:/Finished/Ash vs Evil Dead (Season 01) Goblin/Ash.vs.Evil.Dead.S01E04.XviD.Goblin.[qqss44].avi: target size=349949952, current size=0
2015-11-22 23:02:26.677551 [WARN] [AbstractDiskWriter.cc:476] Making file sparse failed or pending: Incorrect function.
2015-11-22 23:02:26.677551 [DEBUG] [FileAllocationCommand.cc:78] 0 seconds to allocate 1592268800 byte(s)
```


But finaly torrents starts seeding. So the only problem is - why checksum is OK, but aria starts file allocation?

**Comment by tatsuhiro-t** [comment] 2015-11-23 03:34
With 432675e, aria2 now correctly get file size for target file of symlink.

**Comment by amirotin** [comment] 2015-11-23 08:17
Great! It's working! No errors and torrents are seeding! Many thx!

**Comment by tatsuhiro-t** [comment] 2015-11-23 12:32
OK, let's close the issue.

**Closed by tatsuhiro-t** 2015-11-23 12:32 UTC
